from pathlib import Path
import html, json, os, re, shutil

ROOT = Path(__file__).parent
OUT = Path(os.environ.get('OUTPUT_DIR', str(ROOT / 'dist'))).resolve()
if OUT != ROOT / 'dist':
    shutil.copytree(ROOT / 'dist', OUT, dirs_exist_ok=True)
OUT.mkdir(exist_ok=True)
SITE = json.loads((ROOT / 'site.json').read_text(encoding='utf-8'))
SITE_URL = os.environ.get('SITE_URL', SITE['domain']).rstrip('/')
BASE_PATH = os.environ.get('BASE_PATH', '').rstrip('/')

def phone_link(css=''):
    return f'<a class="{css}" href="tel:{SITE["phoneHref"]}">{SITE["phone"]}</a>'

def email_link(css=''):
    return f'<a class="{css}" href="mailto:{SITE["email"]}">{SITE["email"]}</a>'

def icon(name='arrow', size=24):
    paths = {
        'arrow':'<path d="M5 12h14m-6-6 6 6-6 6"/>',
        'up':'<path d="M6 18 18 6M6 6h12v12"/>',
        'check':'<path d="m5 12 4 4L19 6"/>',
        'screen':'<rect x="3" y="4" width="18" height="13" rx="1.5"/><path d="M8 21h8m-4-4v4"/>',
        'laptop':'<path d="M5 16V5h14v11M2 16h20l-1 4H3Z"/>',
        'print':'<path d="M6 8V3h12v5M6 17H3V8h18v9h-3M6 14h12v7H6Z"/><path d="M17 11h1"/>',
        'server':'<rect x="3" y="3" width="18" height="7" rx="1"/><rect x="3" y="14" width="18" height="7" rx="1"/><path d="M7 6.5h1m-1 11h1m5-11h4m-4 11h4"/>',
        'home':'<path d="m3 10 9-7 9 7v11H3ZM9 21v-8h6v8"/>',
        'box':'<path d="m12 3 9 5v9l-9 5-9-5V8Zm0 10v9M3 8l9 5 9-5M7 5.8l9 5"/>',
        'doc':'<path d="M14 2H5v20h14V7Zm0 0v5h5M8 12h8m-8 4h8"/>',
        'chip':'<rect x="6" y="6" width="12" height="12" rx="1"/><path d="M9 2v4m6-4v4M9 18v4m6-4v4M2 9h4m-4 6h4m12-6h4m-4 6h4M10 10h4v4h-4Z"/>',
        'sound':'<path d="M12 4 6 9H3v6h3l6 5Zm4 4a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14"/>',
        'phone':'<path d="m6 3 4 4-2 3c1 3 3 5 6 6l3-2 4 4-2 3C10 22 2 14 3 5Z"/>',
        'mail':'<rect x="3" y="5" width="18" height="14" rx="1"/><path d="m3 6 9 7 9-7"/>',
        'pin':'<path d="M19 10c0 5-7 12-7 12S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2"/>',
        'search-doc':'<path d="M13 3H4v18h7M13 3v5h5V8l-5-5M7 12h3m-3 4h2"/><circle cx="16" cy="15" r="4"/><path d="m19 18 3 3"/>',
        'solution':'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><path d="m14 17 3 3 5-6"/>',
        'proposal':'<path d="M14 2H5v20h14V7Zm0 0v5h5M8 11h4m-4 4h3m1 3 2 2 5-6"/>',
    }
    return f'<svg width="{size}" height="{size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">{paths.get(name,paths["arrow"])}</svg>'

def brand():
    return '<a class="brand" href="/" aria-label="Лигус — главная"><img src="/assets/ligus-logo.svg" width="188" height="63" alt="Лигус"><small>ТЕХНИКА. РЕШЕНИЯ. ПОСТАВКИ.</small></a>'

def header(active=''):
    nav = [('production','Продукция'),('russian-equipment','Российская техника'),('services','Услуги'),('customers','Заказчикам'),('about','О компании'),('contacts','Контакты')]
    links=''.join(f'<a href="/{url}/" {"aria-current=\"page\"" if active==url else ""}>{title}</a>' for url,title in nav)
    return f'''<a class="skip" href="#main">Перейти к содержанию</a><header class="site-header"><div class="nav-shell"><div class="wrap nav-frame"><div class="nav-brand">{brand()}</div><nav class="nav" aria-label="Основная навигация">{links}</nav></div></div><div class="header-main-shell"><div class="header-main wrap">{brand()}<div class="header-contact">{phone_link()}{email_link()}</div><a class="header-cta" href="/request/">Обсудить задачу {icon('up',18)}</a></div></div></header>'''

def footer():
    return f'''<footer><div class="wrap footer-grid"><div>{brand()}<p>Оборудование, которое решает<br>задачи вашей организации.</p><span class="muted">{SITE['geography']}</span></div><div><h3>Направления</h3><a href="/production/">Продукция</a><a href="/russian-equipment/">Российская техника</a><a href="/production/complex/">Комплексное оснащение</a></div><div><h3>Сотрудничество</h3><a href="/services/">Услуги</a><a href="/customers/">Заказчикам</a><a href="/projects/">Проекты</a><a href="/documents/">Документы</a></div><div><h3>Начнём с вашей задачи</h3><a class="footer-action" href="/request/">Отправить ТЗ {icon('up')}</a>{phone_link('footer-phone')}{email_link('footer-email')}<a href="/contacts/">Контакты и реквизиты</a></div></div><div class="wrap footer-bottom"><span>© 2026 Лигус</span><a href="/privacy/">Персональные данные</a><a href="{SITE['domain']}/" target="_blank" rel="noopener">ligus-msk.ru</a></div></footer>'''

def cta(title='Расскажите, что нужно оснастить',text='Пришлите готовое ТЗ или опишите задачу своими словами. Поможем подобрать оборудование и собрать спецификацию.'):
    return f'<section class="cta"><div class="wrap cta-inner"><div><span class="eyebrow">НАЧНЁМ С ЗАДАЧИ</span><h2>{title}</h2><p>{text}</p></div><a class="button white" href="/request/">Получить предложение {icon("up")}</a></div></section>'

def write_page(slug, title, description, content, active='', schema=None):
    target=OUT / slug
    target.mkdir(parents=True,exist_ok=True)
    if schema and schema.get('@type') == 'Organization':
        schema = {**schema, 'url': SITE_URL+'/', 'telephone': SITE['phoneHref'], 'email': SITE['email'], 'areaServed': SITE['areaServed']}
    canonical = SITE_URL + "/" + (slug.strip("/")+"/" if slug else "")
    ld=json.dumps(schema,ensure_ascii=False).replace('</','<\\/') if schema else ''
    (target/'index.html').write_text(f'''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{html.escape(title)}</title><meta name="description" content="{html.escape(description,quote=True)}"><meta name="robots" content="noindex,nofollow"><link rel="canonical" href="{canonical}"><meta property="og:url" content="{canonical}"><meta name="theme-color" content="#2427af"><meta property="og:title" content="{html.escape(title,quote=True)}"><meta property="og:description" content="{html.escape(description,quote=True)}"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/pages.css">{'<script type="application/ld+json">'+ld+'</script>' if ld else ''}<script src="/app.js" defer></script></head><body>{header(active)}<main id="main">{content}</main>{footer()}</body></html>''',encoding='utf-8')

HOME = f'''<section class="hero wrap"><div class="hero-copy"><span class="eyebrow"><span class="blue-dash"></span> ДЛЯ БИЗНЕСА И ГОСУДАРСТВЕННЫХ УЧРЕЖДЕНИЙ</span><h1>Техника под задачи.<br><span>Поставка под ключ.</span></h1><p>Российская компьютерная техника, электроника и бытовое оборудование. От подбора по реестру Минпромторга до оснащения вашего объекта.</p><div class="hero-actions"><a class="button" href="/request/">Подобрать оборудование {icon('up')}</a><a class="text-link" href="/production/">Что мы поставляем {icon('arrow',20)}</a></div><div class="hero-proof"><span>{icon('check',17)} Подбор под ваше ТЗ</span><span>{icon('check',17)} Поставки по России и странам СНГ</span></div></div><div class="hero-visual"><div class="hero-image"></div><div class="visual-caption"><span>ОТ РАБОЧЕГО МЕСТА<br>ДО ЦЕЛОГО ОБЪЕКТА</span><span class="visual-index">01 — 10</span></div></div></section>
<section class="benefits wrap"><div><span>01</span><h3>Российское оборудование</h3><p>Подбор моделей из реестра<br>промышленной продукции</p></div><div><span>02</span><h3>Помощь с документацией</h3><p>Техническое задание, спецификация<br>и коммерческое предложение</p></div><div><span>03</span><h3>Комплексное оснащение</h3><p>Техника для кабинета, учреждения<br>или нового объекта</p></div></section>
<section class="section wrap"><div class="section-heading"><div><span class="eyebrow">НАПРАВЛЕНИЯ ПОСТАВОК</span><h2>Всё необходимое.<br>В одном проекте.</h2></div><p>Подберём комплектацию под вашу задачу,<br>требования и бюджет.</p></div><div class="category-grid">'''

PREVIEW_CATS=[('computers','Компьютеры<br>и моноблоки','screen'),('laptops','Ноутбуки<br>и планшеты','laptop'),('printers','Принтеры<br>и МФУ','print'),('complex','Комплексное<br>оснащение','box')]
HOME+=''.join(f'<a class="category-card" href="/production/{s}/"><span class="category-icon">{icon(i,34)}</span><h3>{t}</h3><span class="category-bottom">Подробнее {icon("up",20)}</span></a>' for s,t,i in PREVIEW_CATS)
HOME+='</div></section>'+cta()
write_page('', 'Лигус — российская техника и комплексное оснащение учреждений', 'Поставка компьютерной техники, электроники и бытового оборудования для организаций. Подбор российской техники из реестра Минпромторга. Россия и страны СНГ.', HOME)

# Presentation content is intentionally separate from the future CMS and delivery services.
CATEGORIES = [
 ('computers','Компьютеры и моноблоки','screen','Рабочие места, готовые к вашим задачам','Российские компьютеры и моноблоки для сотрудников, учебных классов и приёмных. Подберём производительность, форм-фактор и совместимое программное обеспечение.', ['Офисные системные блоки','Компактные мини-ПК','Моноблоки для рабочих мест','Учебные компьютерные классы'], ['Количество рабочих мест и сценарии работы','Требования к процессору, памяти и накопителю','Необходимое ПО и периферия','Условия закупки и требования к реестровой записи']),
 ('laptops','Ноутбуки и планшеты','laptop','Мобильная работа. Продуманная комплектация.','Подбор российских ноутбуков и планшетов для организаций: для выездной работы, преподавания и повседневных задач сотрудников.', ['Ноутбуки для офисных задач','Мобильные рабочие места','Планшеты для выездной работы','Комплекты с док-станциями и аксессуарами'], ['Задачи и используемые программы','Диагональ экрана, вес и автономность','Требуемые порты и способы подключения','Количество устройств и сроки поставки']),
 ('displays','Мониторы и интерактивные панели','screen','Информация, которую видно всем','Мониторы для рабочих мест и интерактивные панели для обучения, презентаций и совместной работы. Поможем подобрать размер, подключение и комплект креплений.', ['Мониторы для сотрудников','Интерактивные панели для классов','Экраны для переговорных','Стойки, крепления и кабели'], ['Размер помещения и расстояние до экрана','Необходимая диагональ и разрешение','Сценарии совместной работы','Совместимость с компьютерами и ПО']),
 ('printers','Принтеры и МФУ','print','Печать под реальную нагрузку','Поставка принтеров, многофункциональных устройств и сканеров для учреждений. Рассчитаем комплектацию с учётом объёма печати и расходных материалов.', ['Монохромные принтеры','МФУ для рабочих групп','Цветная офисная печать','Сканеры и расходные материалы'], ['Среднее количество страниц в месяц','Формат, цветность и двусторонняя печать','Сетевое подключение и совместимость','Требования к расходным материалам']),
 ('servers','Серверы и сетевое оборудование','server','Основа вашей ИТ-инфраструктуры','Подбор серверного и сетевого оборудования под существующую инфраструктуру: вычислительные задачи, хранение данных и подключение рабочих мест.', ['Серверы для прикладных задач','Системы хранения данных','Коммутаторы и маршрутизаторы','Серверные комплектующие'], ['Назначение и ожидаемая нагрузка','Требования к отказоустойчивости','Совместимость с текущей инфраструктурой','Условия размещения и гарантийной поддержки']),
 ('peripherals','Периферия и ИБП','chip','Детали, от которых зависит работа','Периферийное оборудование и источники бесперебойного питания для комплектации рабочих мест. Учтём совместимость и нужный запас мощности.', ['Клавиатуры, мыши и гарнитуры','Источники бесперебойного питания','Веб-камеры и док-станции','Кабели, адаптеры и аксессуары'], ['Модели подключаемого оборудования','Суммарная мощность и время автономии','Разъёмы и интерфейсы','Количество и условия эксплуатации']),
 ('software','Российское программное обеспечение','doc','Совместимая программная среда','Российские операционные системы, офисные приложения и средства защиты для рабочих мест. Подберём лицензии и проверим совместимость с выбранной техникой.', ['Операционные системы','Офисные пакеты','Антивирусное программное обеспечение','Лицензии для организаций'], ['Список прикладных программ','Парк оборудования и число пользователей','Требования к лицензированию','Необходимость проверки в реестре российского ПО']),
 ('electronics','Электроника и мультимедиа','sound','Для встреч, занятий и презентаций','Электроника и мультимедийное оборудование для классов, переговорных и общественных пространств. Соберём совместимый комплект под помещение.', ['Проекторы и экраны','Телевизоры и информационные дисплеи','Акустические системы и микрофоны','Оборудование для видеосвязи'], ['Площадь и особенности помещения','Количество участников','Сценарии использования','Источники сигнала и способы управления']),
 ('appliances','Бытовая техника для учреждений','home','Повседневный комфорт в масштабе объекта','Поставка бытовой техники для школ, детских садов, общежитий, офисов и других организаций. Подберём оборудование под нагрузку и условия размещения.', ['Холодильники и морозильники','Стиральные и сушильные машины','Посудомоечные машины','Мелкая бытовая техника'], ['Тип объекта и количество пользователей','Интенсивность эксплуатации','Габариты и условия подключения','Требования к происхождению оборудования']),
 ('complex','Комплексное оснащение','box','От перечня помещений до готовой поставки','Полное оснащение учреждений компьютерной техникой, электроникой и бытовым оборудованием. Соберём разрозненные потребности в единую спецификацию.', ['Оснащение школ и учебных классов','Техника для медицинских учреждений','Рабочие места для офисов и МФЦ','Комплектация общежитий и социальных объектов'], ['Тип объекта и перечень помещений','Число рабочих мест и пользователей','Общий бюджет и этапность оснащения','Планируемая дата готовности объекта'])
]

def bread(title,parent=None):
    return '<div class="wrap breadcrumb"><a href="/">Главная</a><span>/</span>'+ ('<a href="/production/">Продукция</a><span>/</span>' if parent else '') + f'<span>{title}</span></div>'

def page_intro(label,title,text,parent=None):
    return bread(label,parent)+f'<section class="wrap page-intro"><span class="eyebrow">{label.upper()}</span><h1>{title}</h1><p>{text}</p></section>'

def checklist(items):
    return '<ul class="checklist">'+''.join(f'<li>{icon("check",19)}<span>{i}</span></li>' for i in items)+'</ul>'

def cards(cats=CATEGORIES):
    return '<div class="category-grid">'+''.join(f'<a class="category-card" href="/production/{c[0]}/"><span class="category-icon">{icon(c[2],34)}</span><h3>{c[1]}</h3><span class="category-bottom">Подобрать комплектацию {icon("up",20)}</span></a>' for c in cats)+'</div>'

FAQ=[('Можно обратиться без готового технического задания?','Да. Достаточно описать задачу: для какого объекта нужна техника, сколько пользователей будет с ней работать и какие есть ограничения по бюджету и срокам. На этой основе подготовим перечень оборудования.'),('Как подбирается техника из реестра Минпромторга?','Сначала определяем требования к оборудованию. Затем проверяем конкретную модель и её исполнение по актуальной реестровой записи. Российский бренд сам по себе не означает, что любая его модель включена в реестр.'),('Можно заказать полное оснащение учреждения?','Да. Соберём компьютерную технику, периферию, мультимедиа и бытовое оборудование в одну спецификацию. Состав поставки, установку и сроки согласуем отдельно для вашего объекта.'),('Вы помогаете с закупками по 44-ФЗ и 223-ФЗ?','Помогаем подобрать оборудование, подготовить технические характеристики, спецификацию и коммерческое предложение. Требования конкретной закупки и применимость национального режима согласуем с заказчиком.'),('Почему на сайте нет цен?','Стоимость зависит от комплектации, количества, сроков и условий поставки. Подготовим предложение для вашей задачи с актуальными характеристиками и условиями.')]

def faq(items=FAQ):
    return '<div class="faq">'+''.join(f'<details><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>' for q,a in items)+'</div>'

def steps():
    data=[('Разбираемся в задаче','Изучаем ТЗ или вместе составляем список потребностей.'),('Подбираем решение','Проверяем характеристики, совместимость и реестровые записи.'),('Готовим предложение','Согласуем спецификацию, документы и условия поставки.'),('Комплектуем и поставляем','Организуем доставку и передаём комплект документов.')]
    step_icons = ['search-doc', 'solution', 'proposal', 'box']
    return '<div class="steps">'+''.join(f'<div><div class="step-top"><span>0{i+1}</span>{icon(step_icons[i],44)}</div><h3>{h}</h3><p>{p}</p></div>' for i,(h,p) in enumerate(data))+'</div>'

def request_form(compact=False):
    return f'''<form class="request-form" action="{SITE["formEndpoint"]}" method="POST" enctype="multipart/form-data" novalidate><input type="hidden" name="_subject" value="Лигус — новая заявка с сайта"><input type="hidden" name="_template" value="table"><input type="hidden" name="_next" value="{SITE_URL}/thanks/"><input type="text" name="_honey" class="form-honeypot" tabindex="-1" autocomplete="off" aria-hidden="true"><div class="form-grid"><label>Ваше имя <span>*</span><input name="name" autocomplete="name" placeholder="Как к вам обращаться" required maxlength="100"></label><label>Телефон <span>*</span><input name="phone" type="tel" autocomplete="tel" placeholder="+7 (___) ___-__-__" required maxlength="30"></label><label>Организация<input name="organization" autocomplete="organization" placeholder="Название вашей организации" maxlength="200"></label><label>Электронная почта<input name="email" type="email" autocomplete="email" placeholder="name@company.ru" maxlength="200"></label><label class="full">Ваша задача<textarea name="comment" placeholder="Что нужно поставить, в каком количестве и в какие сроки" rows="4" maxlength="5000"></textarea></label><div class="full"><label class="file-zone" for="spec-file{'-home' if compact else ''}">{icon('doc',23)}<span><strong>Прикрепить техническое задание</strong><small>PDF, DOCX, XLSX, CSV, TXT · один файл до 10 МБ</small></span></label><input class="file-input" id="spec-file{'-home' if compact else ''}" type="file" name="attachment" accept=".pdf,.doc,.docx,.xls,.xlsx,.csv,.txt"><div class="file-info" aria-live="polite"></div></div></div><label class="consent"><input type="checkbox" name="consent" required><span>Я согласен с <a href="/privacy/">условиями обработки данных</a> для ответа на мою заявку.</span></label><div class="form-error" role="alert"></div><button class="button" type="submit">Отправить заявку {icon('up',21)}</button></form>'''

REGISTRY=f'''<section class="registry-section"><div class="wrap registry-grid"><div><span class="eyebrow">РОССИЙСКАЯ ТЕХНИКА</span><h2>Нужна техника<br>из реестра<br><span>Минпромторга?</span></h2><p>Подберём оборудование с учётом требований вашей закупки и проверим реестровые записи для конкретных моделей.</p><a class="button white" href="/russian-equipment/">Как мы подбираем {icon('up',21)}</a></div><div class="registry-process"><span class="eyebrow">ОТ ТРЕБОВАНИЙ К КОНКРЕТНОЙ МОДЕЛИ</span><div><span>01</span><h3>Изучаем ваше ТЗ</h3><p>Характеристики, количество, условия и сроки закупки.</p></div><div><span>02</span><h3>Проверяем по реестру</h3><p>Модель, исполнение и актуальную запись в ГИСП.</p></div><div><span>03</span><h3>Собираем спецификацию</h3><p>Оборудование, комплектность и подтверждающие сведения.</p></div><a href="https://gisp.gov.ru/pp719v2/pub/prod/" target="_blank" rel="noopener" class="registry-source">Реестр промышленной продукции в ГИСП {icon('up',16)}</a></div></div></section>'''

def project_cards():
    data=[('ОБРАЗОВАНИЕ','Компьютерный класс для школы','Московская область','30 рабочих мест','Компьютеры, мониторы, периферия и комплект офисного ПО.','Подбор единой конфигурации для учебного класса, проверка совместимости устройств и подготовка спецификации.','screen'),('ГОСУДАРСТВЕННЫЙ СЕКТОР','Рабочие места для учреждения','Москва','45 комплектов','Моноблоки, МФУ и источники бесперебойного питания.','Комплектация рабочих мест сотрудников и общих зон печати с учётом количества пользователей.','doc'),('КОМПЛЕКСНОЕ ОСНАЩЕНИЕ','Техника для нового общежития','Центральная Россия','3 направления поставки','Компьютерная, мультимедийная и бытовая техника.','Объединение оборудования для административных, жилых и общих помещений в одну ведомость.','home')]
    return '<div class="project-grid">'+''.join(f'<article class="project-card"><div class="project-top"><span>{label}</span>{icon(ico,36)}</div><div class="project-body"><span class="demo-label">ДЕМОНСТРАЦИОННЫЙ ПРИМЕР</span><h3>{title}</h3><div class="project-meta">{region}<span>{num}</span></div><p>{copy}</p><details><summary>Состав решения {icon("arrow",18)}</summary><p>{detail} Это вымышленный пример для согласования сайта.</p></details></div></article>' for label,title,region,num,copy,detail,ico in data)+'</div>'

# Complete home, retaining the initial hero and benefits.
HOME=HOME[:HOME.index('<section class="section wrap">')]
HOME+=f'''<section class="section wrap"><div class="section-heading"><div><span class="eyebrow">НАПРАВЛЕНИЯ ПОСТАВОК</span><h2>Всё необходимое.<br>В одном проекте.</h2></div><a class="text-link" href="/production/">Все направления {icon('arrow',20)}</a></div>{cards(CATEGORIES[:4])}<div class="category-links">{''.join(f'<a href="/production/{c[0]}/">{c[1]} {icon("up",15)}</a>' for c in CATEGORIES[4:])}</div></section>'''
HOME+=REGISTRY
HOME+=f'''<section class="section wrap"><div class="section-heading"><div><span class="eyebrow">ДЛЯ КОГО МЫ РАБОТАЕМ</span><h2>Понимаем задачи<br>вашей организации.</h2></div><p>Учитываем особенности объекта,<br>процедуру закупки и условия эксплуатации.</p></div><div class="audience-grid">{''.join(f'<a href="/customers/#{s}"><span>0{i+1}</span><h3>{t}</h3><p>{p}</p>{icon("up",20)}</a>' for i,(s,t,p) in enumerate([('education','Образование','Школы, детские сады, колледжи и вузы'),('government','Государственные учреждения','Администрации, МФЦ и социальные объекты'),('health','Здравоохранение','Рабочие места и бытовое оснащение учреждений'),('business','Бизнес и подрядчики','Офисы, новые объекты и проектные поставки')]))}</div></section>'''
HOME+=f'<section class="soft-section"><div class="wrap section"><div class="section-heading"><div><span class="eyebrow">КАК МЫ РАБОТАЕМ</span><h2>От задачи до поставки —<br>понятный путь.</h2></div><a class="text-link" href="/services/">Подробнее об услугах {icon("arrow",20)}</a></div>{steps()}</div></section>'
HOME+=f'<section class="section wrap"><div class="section-heading"><div><span class="eyebrow">ПРИМЕРЫ РЕШЕНИЙ</span><h2>Разные объекты.<br>Единый подход.</h2></div><a class="text-link" href="/projects/">Смотреть примеры {icon("arrow",20)}</a></div>{project_cards()}</section>'
HOME+=f'<section class="section wrap faq-layout"><div><span class="eyebrow">ОТВЕЧАЕМ НА ВОПРОСЫ</span><h2>Что важно<br>до закупки.</h2></div>{faq()}</section>'
HOME+=f'<section class="contact-section"><div class="wrap section contact-layout"><div><span class="eyebrow">ОБСУДИМ ВАШУ ЗАДАЧУ</span><h2>Хорошая поставка<br>начинается<br>с разговора.</h2><p>Пришлите ТЗ или опишите потребность. Поможем определиться с оборудованием и комплектацией.</p><div class="contact-location">{icon("pin",23)} Вся Россия и страны СНГ</div><a class="text-link" href="/contacts/">Контакты компании {icon("arrow",18)}</a></div>{request_form(True)}</div></section>'
write_page('', 'Лигус — российская техника и комплексное оснащение учреждений','Российская компьютерная техника, электроника и бытовое оборудование для организаций. Подбор по реестру Минпромторга, ТЗ, спецификация. Поставки по России и странам СНГ.',HOME,schema={'@context':'https://schema.org','@type':'Organization','name':'Лигус','description':'Поставка оборудования для организаций. Демонстрационная версия сайта.','areaServed':['Москва','Россия']})

write_page('production','Продукция для организаций — компьютеры, электроника, бытовая техника | Лигус','10 направлений поставок: компьютеры, ноутбуки, МФУ, серверы, российское ПО и бытовая техника. Подбор под ТЗ и комплексное оснащение.',page_intro('Продукция','От одного рабочего места<br>до целого учреждения.','Компьютерная техника, электроника и бытовое оборудование. Подбираем конкретные модели под вашу задачу, бюджет и требования к закупке.')+f'<section class="wrap section section-compact">{cards()}</section>'+cta(),'production')

for slug,title,ico,headline,desc,types,requirements in CATEGORIES:
    body=page_intro(title,headline,desc,True)
    body+=f'<section class="wrap detail-layout"><div class="detail-main"><span class="eyebrow">ЧТО ПОСТАВЛЯЕМ</span><h2>{title}</h2>{checklist(types)}<div class="info-panel"><span class="info-icon">{icon(ico,35)}</span><div><h3>Комплектация под вашу задачу</h3><p>Конкретные модели, характеристики, количество и стоимость фиксируем в индивидуальном коммерческом предложении. Сроки и условия согласуем до поставки.</p></div></div><h2 class="small-heading">Что нужно для подбора</h2>{checklist(requirements)}</div><aside class="detail-aside"><span class="eyebrow">НАЧНЁМ С ВАШЕГО ТЗ</span><h3>Подберём подходящее решение</h3><p>Готовая спецификация или несколько строк о задаче — достаточно, чтобы начать.</p><a class="button" href="/request/?category={slug}">Запросить КП {icon("up",18)}</a><hr><h4>{"Российское ПО" if slug=="software" else "Российская техника"}</h4><p>{"Для программного обеспечения проверяем сведения в отдельном реестре российского ПО." if slug=="software" else "Если закупка требует российское оборудование, проверяем включение конкретной модели и исполнения в актуальный реестр."}</p><a class="text-link" href="/russian-equipment/">Подробнее о проверке {icon("arrow",17)}</a></aside></section>'
    body+=f'<section class="wrap section"><div class="section-heading"><div><span class="eyebrow">ВМЕСТЕ С ЭТИМ НАПРАВЛЕНИЕМ</span><h2>Дополните комплектацию.</h2></div></div>{cards([c for c in CATEGORIES if c[0]!=slug][:4])}</section>'+cta()
    write_page(f'production/{slug}',f'{title} для организаций и учреждений — поставка | Лигус',desc,body,'production')

registry_body=page_intro('Российская техника','Российская техника.<br><span>С проверкой по реестру.</span>','Поможем подобрать российское оборудование из реестра Минпромторга под ваше техническое задание. Проверяем конкретную модель, её исполнение и соответствие потребности.')
registry_body+=f'<section class="wrap detail-layout"><div class="detail-main"><h2>Отечественный бренд —<br>только начало проверки.</h2><p class="lead">Для закупки важны сведения о конкретной продукции. Мы сопоставляем требования заказчика с характеристиками оборудования и актуальной записью в реестре.</p>{checklist(["Производитель, наименование и исполнение модели","Характеристики оборудования под вашу задачу","Номер и актуальность реестровой записи","Комплектность поставки и подтверждающие сведения"])}<div class="info-panel"><span class="info-icon">{icon("doc",29)}</span><div><h3>Требования зависят от закупки</h3><p>Применимость национального режима и состав подтверждающих документов определяются условиями конкретной закупки. Положения постановления № 1875 и требования к реестровым записям нужно проверять в действующей редакции.</p></div></div></div><aside class="detail-aside"><span class="eyebrow">ПОДБОР ИЗ РЕЕСТРА</span><h3>У вас уже есть техническое задание?</h3><p>Пришлите файл — разберём требования и подберём подходящие позиции.</p><a class="button" href="/request/?category=registry">Подобрать по ТЗ {icon("up",18)}</a></aside></section>'
registry_body+=f'<section class="soft-section"><div class="wrap section"><div class="section-heading"><div><span class="eyebrow">ПОРЯДОК РАБОТЫ</span><h2>Подбор с понятным результатом.</h2></div></div>{steps()}</div></section>'
registry_body+=f'<section class="wrap section"><div class="section-heading"><div><span class="eyebrow">ОСНОВНЫЕ НАПРАВЛЕНИЯ</span><h2>Техника для российских организаций.</h2></div></div>{cards(CATEGORIES[:4])}<div class="source-links"><h3>Официальные источники</h3><a href="https://gisp.gov.ru/pp719v2/pub/prod/" target="_blank" rel="noopener">ГИСП: реестр российской промышленной продукции {icon("up",17)}</a><a href="https://gisp.gov.ru/nmp/measure/8880371" target="_blank" rel="noopener">Подтверждение производства: постановление № 719 {icon("up",17)}</a><a href="https://publication.pravo.gov.ru/document/0001202412250018" target="_blank" rel="noopener">Постановление № 1875: официальная публикация {icon("up",17)}</a><p>Источники приведены для проверки первичных документов. Условия подбора уточняются на дату закупки.</p></div></section>'
registry_body+=f'<section class="wrap section faq-layout"><div><span class="eyebrow">ВОПРОСЫ О РЕЕСТРЕ</span><h2>Разберёмся<br>в деталях.</h2></div>{faq([FAQ[1],FAQ[3],FAQ[0]])}</section>'+cta('Подберём российское оборудование','Опишите задачу и требования к происхождению техники. Начнём с подходящих моделей и реестровых записей.')
write_page('russian-equipment','Техника из реестра Минпромторга для госучреждений | Лигус','Подбор российских компьютеров, ноутбуков, МФУ и другой техники из реестра Минпромторга. Проверка модели и реестровой записи под ваше ТЗ.',registry_body,'russian-equipment',{'@context':'https://schema.org','@type':'FAQPage','mainEntity':[{'@type':'Question','name':q,'acceptedAnswer':{'@type':'Answer','text':a}} for q,a in [FAQ[1],FAQ[3],FAQ[0]]]})

SERVICES=[('Подбор оборудования','Сопоставляем ваши задачи с техническими характеристиками. Учитываем совместимость, условия эксплуатации и бюджет.','Перечень подходящих моделей и комплектаций.'),('Подготовка ТЗ и спецификации','Помогаем описать необходимые характеристики и состав оборудования для вашей закупки.','Структурированная спецификация и проект технических требований.'),('Коммерческое предложение','Готовим актуальное предложение для планирования закупки и расчёта начальной максимальной цены контракта.','КП с характеристиками, количеством, стоимостью и условиями.'),('Комплексное оснащение','Объединяем потребности разных помещений и подразделений в одну поставку.','Согласованная ведомость оборудования по объекту.'),('Доставка и установка','Согласуем маршрут, сроки, разгрузку, а также необходимость установки и первичной настройки.','Оборудование на объекте в согласованной комплектации.'),('Гарантийное сопровождение','Передаём гарантийные документы и помогаем организовать обращение по условиям производителя и договора.','Понятный порядок обращения по поставленному оборудованию.')]
services=page_intro('Услуги','Поможем на каждом этапе.<br>От задачи до оборудования.','Подбор, документация и организация поставки — в одном рабочем процессе. Выберите нужную помощь или доверьте нам комплектацию объекта целиком.')
services+='<section class="wrap service-list">'+''.join(f'<article><span class="service-number">0{i+1}</span><h2>{h}</h2><div><p>{p}</p><span class="result-label">РЕЗУЛЬТАТ</span><p>{r}</p><a class="text-link" href="/request/?service={i}">Обсудить задачу {icon("arrow",17)}</a></div></article>' for i,(h,p,r) in enumerate(SERVICES))+'</section>'+cta()
write_page('services','Подбор оборудования, подготовка ТЗ и комплексное оснащение | Лигус','Помощь с подбором техники, техническими заданиями, спецификациями и КП. Комплексное оснащение, доставка и гарантийное сопровождение.',services,'services')

customers=page_intro('Заказчикам','Поставка с учётом<br>ваших правил закупки.','Работаем с государственными и коммерческими организациями. Согласуем состав оборудования, документы и условия договора до начала поставки.')
customers+='<section class="wrap customer-types">'+''.join(f'<article><span class="big-label">{tag}</span><h2>{title}</h2><p>{desc}</p>{checklist(items)}<a class="text-link" href="/request/">Обсудить закупку {icon("arrow",18)}</a></article>' for tag,title,desc,items in [('44-ФЗ','Государственным заказчикам','Подбор техники для учреждений с учётом технических требований закупки.',['Подбор российских моделей и проверка реестровых записей','Технические характеристики и спецификация','КП для планирования закупки']),('223-ФЗ','Организациям с положением о закупке','Учитываем требования закупочной документации и положения заказчика.',['Согласование комплектности оборудования','Условия, сроки и этапность поставки','Документы по согласованному перечню']),('B2B','Бизнесу и подрядчикам','Техника для открытия нового объекта, обновления офиса и проектных поставок.',['Подбор под задачи сотрудников','Совместимость с текущим оборудованием','Комплексная комплектация объекта'])])+'</section>'
customers+='<section class="soft-section"><div class="wrap section"><div class="section-heading"><h2>Для разных объектов —<br>свой состав оборудования.</h2></div><div class="industry-list">'+''.join(f'<article id="{id}"><h3>{title}</h3><p>{desc}</p></article>' for id,title,desc in [('education','Образование','Учебные классы, рабочие места преподавателей, интерактивные панели и бытовая техника для школ и детских садов.'),('government','Государственные учреждения','Рабочие места сотрудников, приёмные, общие зоны печати и оборудование для переговорных.'),('health','Здравоохранение','Компьютерная техника для административных задач и бытовое оснащение. Состав поставки согласуем под конкретные помещения.'),('business','Бизнес и подрядчики','Офисная техника, мультимедиа и оснащение новых объектов в рамках единой спецификации.')])+'</div></div></section>'+cta()
write_page('customers','Поставка техники по 44-ФЗ, 223-ФЗ и для бизнеса | Лигус','Оборудование для государственных, бюджетных и коммерческих организаций. Помощь с подбором, ТЗ и документацией к поставке.',customers,'customers')

about=page_intro('О компании','Лигус. Объединяем технику<br>в работающие решения.','Помогаем организациям подобрать и закупить оборудование: от отдельных рабочих мест до комплексного оснащения объекта. Работаем из Москвы с заказчиками по всей России и в странах СНГ.')
about+=f'<section class="wrap about-layout"><div class="about-image"><img src="/assets/equipment.webp" alt="Иллюстрация компьютерного и офисного оборудования" loading="lazy" width="1122" height="1402"><small>Концептуальное изображение оборудования</small></div><div><span class="eyebrow">НАШ ПОДХОД</span><h2>Сначала задача.<br>Потом — комплектация.</h2><p>У каждого объекта свои требования. Поэтому работу начинаем с вопросов о задачах, пользователях, бюджете и сроках. После этого подбираем технику и собираем спецификацию.</p><p>Особое внимание уделяем российскому оборудованию. Если закупка требует включения продукции в реестр Минпромторга, проверяем конкретные модели и исполнения.</p>{checklist(["Один контакт по составу и условиям поставки","Понятное коммерческое предложение","Комплектация компьютерной, электронной и бытовой техники"])}<a class="button" href="/contacts/">Связаться с нами {icon("up",18)}</a></div></section>'
about+=f'<section class="wrap section"><div class="company-links"><a href="/projects/"><h3>Проекты и решения</h3><p>Примеры оснащения разных объектов.</p>{icon("up")}</a><a href="/documents/"><h3>Документы</h3><p>Материалы для начала сотрудничества.</p>{icon("up")}</a><a href="/contacts/"><h3>Контакты и реквизиты</h3><p>Москва и поставки по России и странам СНГ.</p>{icon("up")}</a></div></section>'+cta()
write_page('about','О компании Лигус — поставка техники по России и странам СНГ','Лигус: подбор компьютерной техники, электроники и бытового оборудования для учреждений. Российская техника и комплексное оснащение.',about,'about')

projects=page_intro('Проекты','Отдельные задачи.<br>Комплексные решения.','Примеры того, как может выглядеть оснащение школы, учреждения или нового объекта. После согласования заменим их реальными поставками «Лигус».')+f'<section class="wrap section section-compact"><div class="demo-banner">Все проекты ниже вымышлены и показывают структуру будущих кейсов.</div>{project_cards()}</section>'+cta()
write_page('projects','Примеры комплексного оснащения учреждений | Лигус','Демонстрационные примеры комплектации школ, учреждений и общежитий. Компьютерная техника, электроника и бытовое оснащение.',projects,'about')

docs=page_intro('Документы','Всё для начала<br>сотрудничества.','Шаблоны помогут собрать исходные данные для подбора. Регистрационные документы компании и подтверждения партнёрства добавим после получения оригиналов.')
docs+='<section class="wrap section section-compact"><div class="document-list"><a href="/documents/equipment-template.csv" download><span class="document-format">CSV</span><div><h3>Шаблон перечня оборудования</h3><p>Помещение, оборудование, количество и требования</p></div><span>Скачать '+icon('arrow',20)+'</span></a><a href="/documents/company-demo.txt" download><span class="document-format">TXT</span><div><h3>Карточка компании · образец</h3><p>Структура реквизитов для заполнения</p></div><span>Скачать '+icon('arrow',20)+'</span></a></div><div class="info-panel"><span class="info-icon">'+icon('doc',30)+'</span><div><h3>Сертификаты и партнёрские письма</h3><p>Раздел подготовлен для подлинных документов. Демонстрационные сертификаты и вымышленные статусы партнёра здесь не публикуются.</p></div></div></section>'+cta()
write_page('documents','Документы и шаблоны для подбора оборудования | Лигус','Шаблон перечня оборудования и структура карточки компании. Подготовка исходных данных для технического задания и коммерческого предложения.',docs,'about')
(OUT/'documents/equipment-template.csv').write_text('\ufeffПомещение;Оборудование;Количество;Технические требования;Требование к реестру;Срок\nУчебный класс;Компьютер;30;Указать характеристики;Уточнить;Уточнить\nКабинет;МФУ;1;Указать объём печати;Уточнить;Уточнить\n',encoding='utf-8')
(OUT/'documents/company-demo.txt').write_text('ДЕМОНСТРАЦИОННАЯ КАРТОЧКА. НЕ ИСПОЛЬЗОВАТЬ ДЛЯ ОПЛАТЫ.\nБренд: Лигус\nЮридическое наименование: [указать]\nИНН / КПП: [указать]\nОГРН: [указать]\nЮридический адрес: [указать]\nБанковские реквизиты: [указать]\nКонтактное лицо: [указать]\nТелефон: +7 977 977 22 31\nEmail: tender@ligus-msk.ru\nСайт: http://ligus-msk.ru/\nГеография: Вся Россия и страны СНГ\n',encoding='utf-8')

contacts=page_intro('Контакты','Давайте обсудим<br>вашу следующую поставку.','Вся Россия и страны СНГ. Можно начать с короткого описания задачи или сразу подготовить техническое задание на просчёт.')
contacts+=f'<section class="wrap contacts-grid"><div class="contacts-card"><span class="eyebrow">ОТДЕЛ ПОСТАВОК</span><div class="contact-item">{icon("phone",23)}<div><span>Телефон</span><strong>{phone_link()}</strong></div></div><div class="contact-item">{icon("mail",23)}<div><span>Электронная почта</span><strong>{email_link()}</strong></div></div><div class="contact-item">{icon("pin",23)}<div><span>География</span><strong>Вся Россия и страны СНГ</strong></div></div><p>Рабочее время · образец<br><b>Пн–Пт, 09:00–18:00 по Москве</b></p><a class="button" href="/request/">Подготовить заявку {icon("up",19)}</a></div><div class="requisites"><span class="eyebrow">РЕКВИЗИТЫ</span><h2>Информация о компании</h2><dl><div><dt>Бренд</dt><dd>Лигус</dd></div><div><dt>Сайт</dt><dd><a href="{SITE["domain"]}/" target="_blank" rel="noopener">ligus-msk.ru</a></dd></div><div><dt>Юридическое лицо</dt><dd>Будет добавлено</dd></div><div><dt>ИНН / КПП</dt><dd>Будут добавлены</dd></div><div><dt>ОГРН</dt><dd>Будет добавлен</dd></div><div><dt>Адрес офиса</dt><dd>Москва, адрес уточняется</dd></div></dl></div></section>'+cta()
write_page('contacts','Контакты Лигус — Москва и поставки по России и странам СНГ','Обсудите подбор и поставку техники для вашей организации. Вся Россия и страны СНГ. Телефон +7 977 977 22 31. Почта tender@ligus-msk.ru.',contacts,'contacts')

request=page_intro('Заявка','Ваша задача.<br><span>Наше решение.</span>','Прикрепите техническое задание или опишите, что нужно вашей организации. Подберём оборудование, уточним комплектность и подготовим предложение.')
request+=f'<section class="wrap request-layout"><div><span class="eyebrow">ЧТО ПРОИЗОЙДЁТ ДАЛЬШЕ</span><ol class="request-steps"><li><span>01</span><div><h3>Разберём вашу задачу</h3><p>Уточним детали и требования к оборудованию.</p></div></li><li><span>02</span><div><h3>Подберём комплектацию</h3><p>Проверим характеристики и реестровые записи.</p></div></li><li><span>03</span><div><h3>Подготовим предложение</h3><p>Состав, стоимость и условия поставки.</p></div></li></ol></div>{request_form()}</section>'
write_page('request','Запросить КП и отправить ТЗ на подбор техники | Лигус','Опишите задачу и приложите техническое задание для подбора оборудования. Комплектация, российская техника и поставка по России и странам СНГ.',request)

thanks=f'<section class="wrap thankyou"><span class="success-icon">{icon("check",35)}</span><span class="eyebrow">СПАСИБО ЗА ОБРАЩЕНИЕ</span><h1>Заявка передана.</h1><p>Свяжемся с вами по указанным контактам и уточним детали. Если вопрос срочный, позвоните {phone_link()} или напишите {email_link()}.</p><div class="hero-actions"><a class="button" href="/production/">Посмотреть оборудование {icon("arrow",19)}</a><a class="text-link" href="/request/">Отправить ещё одну заявку</a></div></section>'
write_page('thanks','Спасибо за обращение | Лигус','Спасибо за обращение в Лигус. Уточним задачу и подготовим предложение по оборудованию.',thanks)

privacy=page_intro('Персональные данные','Как обрабатываются<br>данные вашей заявки.','Отправляя форму, вы передаёте контактные данные и описание задачи, чтобы команда «Лигус» могла ответить на обращение и подготовить предложение.')
privacy+=f'<section class="wrap prose section-compact"><h2>Какие данные вы передаёте</h2><p>Имя, телефон, название организации, электронную почту, описание задачи и выбранный файл. Для обращения обязательны имя, телефон и согласие с этими условиями; остальные сведения вы добавляете по желанию.</p><h2>Кому поступает заявка</h2><p>Заявка направляется команде «Лигус» на {email_link()}. Для передачи используется внешний сервис FormSubmit. Он обрабатывает поля формы и вложение и пересылает их на указанный адрес.</p><h2>Хранение у обработчика</h2><p>Согласно документации FormSubmit, сведения об обращениях сохраняются в его архиве в течение 30 дней. Загруженные файлы в этот архив не входят. Условия сервиса: <a href="https://formsubmit.co/documentation" target="_blank" rel="noopener">документация FormSubmit</a>.</p><h2>Цель использования</h2><p>Данные используются для связи по вашей заявке, уточнения характеристик, подготовки коммерческого предложения и обсуждения условий поставки. Форма не подписывает вас на рекламную рассылку.</p><h2>Связаться по вопросам данных</h2><p>По вопросам обработки или удаления сведений напишите {email_link()}. Данные об операторе и сроки хранения переписки в компании будут уточнены после добавления юридических реквизитов.</p><h2>Работа сайта</h2><p>На сайте нет рекламных счётчиков и коллтрекинга. Хостинг и сервис обработки форм могут вести собственные технические журналы в соответствии со своими условиями.</p></section>'
write_page('privacy','Условия обработки данных заявки | Лигус','Какие данные получает Лигус из формы, для чего они используются и как обратиться по вопросам обработки.',privacy)

write_page('404','Страница не найдена | Лигус','Запрошенная страница не найдена.',f'<section class="wrap thankyou"><span class="eyebrow">404</span><h1>Этой страницы нет.</h1><p>Перейдите к направлениям поставок или начните с главной.</p><a class="button" href="/">На главную {icon("arrow",18)}</a></section>')
(OUT/'404.html').write_text((OUT/'404/index.html').read_text(),encoding='utf-8')
(OUT/'robots.txt').write_text('User-agent: *\nDisallow: /\n',encoding='utf-8')
routes=sorted('/'+str(p.parent.relative_to(OUT)).replace('\\','/')+'/' for p in OUT.rglob('index.html') if p.parent!=OUT and p.parent.name not in ['404','thanks','privacy'])
(ROOT/'routes.json').write_text(json.dumps(['/']+routes,ensure_ascii=False,indent=2),encoding='utf-8')
print(f'Built {len(list(OUT.rglob("index.html")))} pages in {OUT}')

# Approved logo + revised editorial direction from the user's visual reference.
EDITORIAL_HERO=f'''<section class="hero-editorial"><div class="editorial-image" aria-hidden="true"></div><div class="wrap editorial-hero-content"><span class="eyebrow">РОССИЙСКАЯ ТЕХНИКА. КОМПЛЕКСНЫЕ ПОСТАВКИ.</span><h1>Технологии для работы.<br>Решения для развития.</h1><p>Поставляем компьютерную технику, электронику<br>и бытовое оборудование для бизнеса<br>и государственных учреждений.</p><a class="button white" href="/request/">Подобрать оборудование <span aria-hidden="true">↗</span></a></div><div class="editorial-hero-bottom"><div class="wrap hero-bottom-inner"><span>{SITE['geography']}</span><a href="/russian-equipment/">Техника из реестра {icon('up',18)}</a></div></div></section>
<section class="statement" id="approach"><div class="statement-label"><span class="eyebrow">01 / ПОДХОД</span><span>ВНИМАНИЕ К КАЖДОЙ ДЕТАЛИ</span></div><div class="statement-body"><h2>Мы помогаем организациям<br>выбирать технику, которая<br>решает их задачи. Объединяем<br>оборудование, документацию<br>и поставку в понятный процесс.</h2><a class="button" href="/about/">Ближе познакомиться {icon('up',16)}</a><span class="statement-sign">ЛИГУС — ТЕХНИКА И РЕШЕНИЯ</span></div></section>'''
editorial=EDITORIAL_HERO+HOME[HOME.index('<section class="section wrap">'):]
editorial=editorial.replace('<section class="section wrap"><div class="section-heading"><div><span class="eyebrow">НАПРАВЛЕНИЯ ПОСТАВОК</span>', '<section class="section wrap product-editorial"><div class="section-heading"><div><span class="eyebrow">02 / НАПРАВЛЕНИЯ ПОСТАВОК</span>',1)
write_page('', 'Лигус — российская техника и комплексное оснащение учреждений','Российская компьютерная техника, электроника и бытовое оборудование. Подбор по реестру Минпромторга, ТЗ и спецификация. Вся Россия и страны СНГ.',editorial,schema={'@context':'https://schema.org','@type':'Organization','name':'Лигус','description':'Поставка оборудования для организаций. Демонстрационная версия сайта.','areaServed':['Москва','Россия']})
for page in list(OUT.rglob('index.html'))+[OUT/'404.html']:
    text=page.read_text().replace('</head>','<link rel="stylesheet" href="/editorial.css"><link rel="stylesheet" href="/refinements.css"></head>').replace('<br>','<br> ')
    if page==OUT/'index.html': text=text.replace('<body>','<body class="editorial-home">')
    text = text.replace('<meta name="viewport"', f'<meta name="site-base" content="{BASE_PATH}"><meta name="viewport"')
    if BASE_PATH:
        text = re.sub(r'(href|src|action)="(/(?!/)[^"]*)"', lambda m: f'{m[1]}="{BASE_PATH}{m[2]}"', text)
    page.write_text(text,encoding='utf-8')
if BASE_PATH:
    for css in OUT.glob('*.css'):
        text = re.sub(r'url\((\x27|\x22)?(/(?!/)[^)]*)\)', lambda m: 'url('+(m[1] or '')+BASE_PATH+m[2]+')', css.read_text())
        css.write_text(text, encoding='utf-8')
(OUT / '.nojekyll').touch()
(OUT / 'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+''.join(f'<url><loc>{html.escape(SITE_URL+route)}</loc></url>\n' for route in ['/']+routes)+'</urlset>\n', encoding='utf-8')
